---
- name: Install Apache2
  become: yes
  with_items: "{{ apache2_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: Copy wordpress.conf virtual hosts file
  become: yes
  template:
    src: ../templates/default-site.conf.j2
    dest: /etc/apache2/sites-available/default-site.conf
    owner: www-data
    group: www-data
    mode: 0644

- name: Enable WordPress site with symbolic link
  become: yes
  file:
    src: /etc/apache2/sites-available/default-site.conf
    dest: /etc/apache2/sites-enabled/default-site.conf
    force: yes
    owner: www-data
    group: www-data
    state: link

- name: Disable default site
  become: yes
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart web service

- name: Enable required Apache modules
  become: yes
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - rewrite
    - ssl
