---

- name: Install php extensions
  become: yes
  with_items: "{{ fedora_php_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: present


- name: Setup php-cgi
  become: yes
  replace:
    dest: /etc/php.ini
    regexp: "(;cgi.fix_pathinfo=1)"
    replace: "cgi.fix_pathinfo=0"

- name: set http in firewall
  become: yes
  firewalld:
    service: http
    permanent: yes
    zone: public
    state: enabled

- name: set tcp in firewall
  become: yes
  firewalld:
    port: 443/tcp
    permanent: yes
    zone: public
    state: enabled

- name: Reload firewall
  become: yes
  command: firewall-cmd --reload
