---

- name: Install php extensions
  become: yes
  with_items: "{{ fedora_php_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: present


- name: Setup php-cgi
  become: yes
  replace:
    dest: /etc/php/7.3/cgi/php.ini
    regexp: "(;cgi.fix_pathinfo=1)"
    replace: "cgi.fix_pathinfo=0"
